spring.datasource.url=jdbc:postgresql://localhost:5432/udomi
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/api-dokumentacija.html