spring.datasource.url=jdbc:postgresql://localhost:5432/udomi
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
openai.chatgtp.model=gpt-3.5-turbo
openai.chatgtp.api.key=DODAJ SVOJ KEY :D
openai.chatgtp.api.url=https://api.openai.com/v1/chat/completions

openai.chatgtp.max-completions=1
openai.chatgtp.temperature=0
openai.chatgtp.max_tokens=100

#key i url za slack
slack.bearer.token=xoxb-6645280768823-6682637370816-CjKPscPJ8wIvqalVCPpH34Gx
slack.url=https://slack.com/api/chat.postMessage

springdoc.swagger-ui.path=/api-dokumentacija.html